spring.application.name=forohub

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.security.user.name=admin
spring.security.user.password=123456

api.security.secret=${JWT_SECRET:12345678}}
