CREATE TABLE usuarios (
id BIGINT NOT NULL AUTO_INCREMENT,
login VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(300) NOT NULL,
activo TINYINT NOT NULL DEFAULT 1, -- Usamos 1 para true en MySQL

PRIMARY KEY(ID)
);